---
- name: This playbook installs a package
  hosts: webservers
  become: true
  tasks:
  - name: Installing httpd package
    yum:
      name: httpd
      state: installed

  - name: Starting httpd service
    service:
      name: httpd
      state: started
