---
- name: setup tomcat
  hosts: all
  become: true

  tasks:
  - name: Install java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Install java on Debian
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat
    get_url:
      url: https://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.66/bin/apache-tomcat-8.5.66.tar.gz
      dest: /opt

  - name: Extract tomcat package
    unarchive:
      src: /opt/apache-tomcat-8.5.66.tar.gz
      dest: /opt
      remote_src: yes

  - name: Give Exec permissions
    file:
      path: /opt/apache-tomcat-8.5.66/bin/startup.sh
      mode: 0777

  - name: Start Tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.66/bin







